{{- $fullName := include "boundary-chart.fullname" . }}
{{- $labels := include "boundary-chart.labels" . }}
{{- $selectorLabels := include "boundary-chart.selectorLabels" . }}
{{- $publicPort := .Values.publicPort }}
{{- range $index, $service := .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ $index }}
  labels:
    {{- $labels | nindent 4 }}
{{- if $service.annotations }}
  annotations:
  {{- range $key, $value := $service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: {{ $service.type }}
  {{- $type := $service.type }}
  ports:
    {{- range $service.ports }}
    - port: {{ .number }}
      targetPort: {{ .name }}
      {{- if eq $type "NodePort" }}
      nodePort: {{ default 30202 $publicPort }}
      {{- end }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
{{- if $service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml $service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  selector:
    {{- $selectorLabels | nindent 4 }}
{{- end }}

---

{{ if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-metrics
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    prometheus.io/path: {{ .Values.metrics.path }}
    prometheus.io/port: {{ .Values.metrics.port | quote }}
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.name }}
      protocol: TCP
      name: {{ .Values.metrics.name }}
  selector:
    {{- $selectorLabels | nindent 4 }}
{{- end }}
